# Generated by Django 5.1.5 on 2025-01-28 20:15

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Park Name')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTypes',
            fields=[
                ('reg_type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Registration Type')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('cost', models.IntegerField(verbose_name='Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Role')),
                ('description', models.TextField(verbose_name='Role Description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Team Name')),
                ('place', models.IntegerField(default=0, verbose_name='Place')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='wioblapp.player')),
                ('reg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='wioblapp.registrationtypes')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='wioblapp.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date')),
                ('team1_score', models.IntegerField(blank=True, null=True, verbose_name='Team #1 Score')),
                ('team2_score', models.IntegerField(blank=True, null=True, verbose_name='Team #2 Score')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='wioblapp.park')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_games', to='wioblapp.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_games', to='wioblapp.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='wioblapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(verbose_name='Bio')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_accounts', to='wioblapp.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(related_name='teams', to='wioblapp.useraccount'),
        ),
        migrations.AddField(
            model_name='player',
            name='related_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='wioblapp.useraccount'),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_content', models.CharField(max_length=100, verbose_name='Flagged Content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flags', to='wioblapp.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wioblapp.game')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='wioblapp.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='announcements', to='wioblapp.useraccount')),
            ],
        ),
    ]
