# Generated by Django 5.1.5 on 2025-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0002_alter_useraccount_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
