# Generated by Django 5.1.5 on 2025-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0003_announcement_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requests'),
        ),
    ]
