# Generated by Django 5.1.5 on 2025-02-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0004_team_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
    ]
