# Generated by Django 5.1.5 on 2025-02-04 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0006_remove_registration_gender_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='wioblapp.team'),
        ),
    ]
