# Generated by Django 5.1.5 on 2025-02-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0007_alter_player_team_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationTypes',
            new_name='RegistrationType',
        ),
    ]
