# Generated by Django 5.1.5 on 2025-02-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0008_rename_registrationtypes_registrationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Adress'),
        ),
    ]
