# Generated by Django 5.1.5 on 2025-02-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0009_alter_team_coaches"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
