# Generated by Django 5.1.5 on 2025-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0011_remove_role_phone_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Team Color'),
        ),
    ]
