# Generated by Django 5.1.5 on 2025-02-11 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0012_team_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="coaches",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
