# Generated by Django 5.1.5 on 2025-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0013_alter_team_coaches"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
