# Generated by Django 5.1.5 on 2025-02-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0014_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flagged_content',
            field=models.CharField(max_length=1000, verbose_name='Flagged Content'),
        ),
    ]
