# Generated by Django 5.1.5 on 2025-02-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0014_registration_team'),
        ('wioblapp', '0015_alter_flag_flagged_content'),
    ]

    operations = [
    ]
