# Generated by Django 5.1.5 on 2025-02-16 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0017_likedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='wioblapp.comment'),
        ),
    ]
