# Generated by Django 5.1.5 on 2025-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0021_remove_flag_flagged_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="park",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
