# Generated by Django 5.1.5 on 2025-02-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0021_remove_flag_flagged_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flag",
            name="comment",
        ),
        migrations.AddField(
            model_name="flag",
            name="flagged_content",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Flagged Content"
            ),
        ),
    ]
