# Generated by Django 5.1.5 on 2025-02-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0022_remove_flag_comment_flag_flagged_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="wioblapp.comment",
            ),
        ),
    ]
