# Generated by Django 5.1.5 on 2025-02-18 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0023_alter_park_latitude_alter_park_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
