# Generated by Django 5.1.5 on 2025-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0024_remove_flag_flagged_content"),
        ("wioblapp", "0025_alter_game_team1_score_alter_game_team2_score_and_more"),
    ]

    operations = []
