# Generated by Django 5.1.5 on 2025-02-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wioblapp', '0026_merge_20250218_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bio',
        ),
    ]
