# Generated by Django 5.1.5 on 2025-02-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wioblapp", "0027_remove_useraccount_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriteteams",
                        to="wioblapp.team",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriteteams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
